# .streamlit/secrets.toml

[database]
# Copy the "Transaction pooler" URI from your Supabase project’s Connect modal
url = "postgresql://postgres:Apple1317..!!@db.cypkfsuwwyifpaiqvvjg.supabase.co:6543/postgres?sslmode=require"

[email]
sender   = "tgalente15@gmail.com"
receiver = "tgalente15@gmail.com"
password = "gxlxqiuahqfeahgk"